### ISSUE TITLE
Strg U Menü

### ISSUE THREAD

**Issue by wartheatre** [TaskForce47/BMR_Insurgency.Altis#17]
Beim Frequenz Menü ist zwar ein Eintrag in der Liste möglich, jedoch erscheint der Marker nicht auf der Map.

**Comment by ghost** [comment]
Hier wird in naher Zukunft ein neues System eingebaut daher wontfix

**Comment by phumberdroz** [comment]
kein Insurgency issue sondern ein module problem.
